const express = require('express');
let books = require("./booksdb.js");
let isValid = require("./auth_users.js").isValid;
let users = require("./auth_users.js").users;
const public_users = express.Router();

// User registration endpoint
public_users.post("/register", (req, res) => {
    const username = req.body.username;
        const password = req.body.password;

            if (!username || !password) {
                    return res.status(400).json({ message: "Username and password are required" });
                        }

                            const userExists = users.some((user) => user.username === username);
                                if (userExists) {
                                        return res.status(409).json({ message: "Username already exists!" });
                                            }

                                                users.push({ "username": username, "password": password });
                                                    return res.status(201).json({ message: "User successfully registered. Now you can login" });
                                                    });

                                                    // ==========================================
                                                    // REFACTORED ASYNC ENDPOINTS (TASKS 10-13)
                                                    // ==========================================

                                                    // Task 10: Get the list of books available in the shop using Async/Await
                                                    public_users.get('/', async function (req, res) {
                                                        try {
                                                                // Simulating an asynchronous database fetch via a Promise
                                                                        const fetchBooks = () => new Promise((resolve) => resolve(books));
                                                                                const availableBooks = await fetchBooks();
                                                                                        
                                                                                                return res.status(200).send(JSON.stringify({ books: availableBooks }, null, 4));
                                                                                                    } catch (error) {
                                                                                                            return res.status(500).json({ message: "Error retrieving book list", error: error.message });
                                                                                                                }
                                                                                                                });

                                                                                                                // Task 11: Get book details based on ISBN using Async/Await
                                                                                                                public_users.get('/isbn/:isbn', async function (req, res) {
                                                                                                                    const isbn = req.params.isbn;
                                                                                                                        try {
                                                                                                                                const fetchBookByISBN = () => new Promise((resolve, reject) => {
                                                                                                                                            const book = books[isbn];
                                                                                                                                                        if (book) resolve(book);
                                                                                                                                                                    else reject("Book not found");
                                                                                                                                                                            });

                                                                                                                                                                                    const bookDetails = await fetchBookByISBN();
                                                                                                                                                                                            return res.status(200).send(JSON.stringify(bookDetails, null, 4));
                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                        return res.status(404).json({ message: error });
                                                                                                                                                                                                            }
                                                                                                                                                                                                            });
                                                                                                                                                                                                              
                                                                                                                                                                                                              // Task 12: Get book details based on Author using Async/Await
                                                                                                                                                                                                              public_users.get('/author/:author', async function (req, res) {
                                                                                                                                                                                                                  const authorParam = req.params.author.toLowerCase();
                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                              const fetchBooksByAuthor = () => new Promise((resolve) => {
                                                                                                                                                                                                                                          const keys = Object.keys(books);
                                                                                                                                                                                                                                                      let matchingBooks = [];
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                              keys.forEach((key) => {
                                                                                                                                                                                                                                                                                              if (books[key].author.toLowerCase() === authorParam) {
                                                                                                                                                                                                                                                                                                                  matchingBooks.push({
                                                                                                                                                                                                                                                                                                                                          isbn: key,
                                                                                                                                                                                                                                                                                                                                                                  author: books[key].author,
                                                                                                                                                                                                                                                                                                                                                                                          title: books[key].title,
                                                                                                                                                                                                                                                                                                                                                                                                                  reviews: books[key].reviews
                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              resolve(matchingBooks);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const results = await fetchBooksByAuthor();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (results.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return res.status(200).send(JSON.stringify(results, null, 4));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return res.status(404).json({ message: "No books found by this author" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return res.status(500).json({ message: "Internal server error" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Task 13: Get book details based on Title using Async/Await
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              public_users.get('/title/:title', async function (req, res) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const titleParam = req.params.title.toLowerCase();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const fetchBooksByTitle = () => new Promise((resolve) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const keys = Object.keys(books);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      let matchingBooks = [];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  keys.forEach((key) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (books[key].title.toLowerCase() === titleParam) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      matchingBooks.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              isbn: key,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      author: books[key].author,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: books[key].title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      reviews: books[key].reviews
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  resolve(matchingBooks);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const results = await fetchBooksByTitle();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (results.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return res.status(200).send(JSON.stringify(results, null, 4));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return res.status(404).json({ message: "No books found with this title" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return res.status(500).json({ message: "Internal server error" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Task 5: Get book review (Remained standard route handler)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  public_users.get('/review/:isbn', function (req, res) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const isbn = req.params.isbn;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const book = books[isbn];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (book) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return res.status(200).send(JSON.stringify(book.reviews, null, 4));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return res.status(404).json({ message: "Book not found" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      module.exports.general = public_users;